import Head from "next/head";
import { useCountires } from "../context/CountriesContext";

export default function Home() {
  const [countries, setCountries] = useCountires();
  console.log(countries);
  return (
    <div>
      <Head>
        <title>Rest Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {countries.map((country) => (
        <p>{country.name}</p>
      ))}
    </div>
  );
}
