import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import { useAllCountries, useCountries } from "../context/CountriesContext";
import Input from "../components/Input";

export default function Home() {
  const [countries, setCountries] = useCountries();
  const [all, setAll] = useAllCountries();
  const [region, setRegion] = useState("");

  useEffect(() => {
    if (region === "") {
      setCountries(all);
    } else {
      const tempCountries = all.filter(
        (c) => c.region.toLowerCase() === region
      );
      setCountries(tempCountries);
    }
  }, [region]);

  return (
    <div>
      <Head>
        <title>Rest Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Layout>
        <Input region={region} />
        <div onClick={() => setRegion("")}>all</div>
        <div onClick={() => setRegion("africa")}>africa</div>
        <div onClick={() => setRegion("americas")}>america</div>
        <div onClick={() => setRegion("asia")}>asia</div>
        <div onClick={() => setRegion("europe")}>europe</div>
        <div onClick={() => setRegion("oceania")}>oceania</div>
        {countries.map((country) => (
          <Link href={`/details/${country.name.toLowerCase().replace(" ", "-")}`}>
            {country.name}
          </Link>
        ))}
      </Layout>
    </div>
  );
}
